{
 "title": "Rideshare Example (Reference)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Monitoring Workshop\n\n## Workshop links\n\n- [rideshare-app (us-east-1)](http://localhost:5050)\n- [vmalert](http://localhost:8880)\n- [alertmanager](http://localhost:9093)\n\n## Other links (for fun)\n\n- [grafana](http://localhost:3000)\n- [alloy](http://localhost:12345)\n- [pyroscope](http://localhost:4040)\n- [gatus](http://localhost:8888)"
   }
  },
  { "title": "store-api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(go_app_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(go_app_http_requests_total{service_name=~\"workshop.*\", status_code=~\"5..\"}[5m]))\n/\nsum(rate(go_app_http_requests_total{service_name=~\"workshop.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "sum(\nrate(go_app_http_request_duration_seconds_sum{service_name=~\"workshop.*\", path!=\"/favicon.ico\"}[5m])\n/\nrate(go_app_http_request_duration_seconds_count{service_name=~\"workshop.*\", path!=\"/favicon.ico\"}[5m])\n) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rideshare order logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"workshop.*\"} |= `order`"
    }
   ]
  },
  {
   "title": "Rideshare error logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"workshop.*\"} |= `error`"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "filters": [
      { "id": "4b6cd61c", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "load-generator" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Alert rule (5XX errors)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(go_app_http_requests_total{service_name=~\"workshop.*\", status_code=~\"5..\"}[5m]))\n/\nsum(rate(go_app_http_requests_total{service_name=~\"workshop.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}