{
 "title": "Monitoring Workshop",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Monitoring Workshop\n\n## Workshop links\n\n- [store-app](http://localhost:8081)\n- [store-api](http://localhost:8080)\n- [vmalert](http://localhost:8880)\n- [alertmanager](http://localhost:9093)\n\n## Other links"
   }
  },
  { "title": "store-api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(go_app_http_requests_total{service_name=\"store-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "go_app_http_request_duration_seconds_sum{service_name=\"store-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "store-api product request logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"store-api\"} |= ``"
    }
   ]
  }
 ]
}