global:
  resolve_timeout: 5m

route:
  group_by:
    - "alertname"
    - "severity"
    - "owner_team"
    - "service_name"

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "noalerts"

# For the sake of this workshop, alerts will not route anywhere, we will use AlertManager to show that alerts have been triggered from the alert rules.
receivers:
  # /dev/null receiver, used to effectively disable alerting for specific usecases
  - name: noalerts
