name: monitoring-workshop
services:
# Metrics Backend - VictoriaMetrics
# Logging Backend - Grafana Loki

# Data Collection - Grafana Alloy
  grafana_alloy:
    image: grafana/alloy:v1.7.4
    container_name: grafana_alloy
    labels:
      ca.j6n.docker.metrics_enabled: "true"
      ca.j6n.docker.logging_enabled: "true"
    volumes:
      - ./data/grafana_alloy/config/config.alloy:/etc/alloy/config.alloy
      - ./data/grafana_alloy/data:/var/lib/alloy/data
      # Allow alloy to talk to docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 12345:12345
    restart: 'unless-stopped'
    command: 'run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy'
# Alerts - Prometheus AlertManager
# Querying and Visualizations - Grafana
  grafana:
    image: grafana/grafana:v12.0.2
    container_name: grafana
    labels:
      ca.j6n.docker.metrics_enabled: "true"
      ca.j6n.docker.logging_enabled: "true"
    volumes:
      - ./data/grafana/config/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    restart: 'unless-stopped'
